trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '8df577e0-5bd6-4182-ab1c-e3048bd51b2b'

  # Function app name
  functionAppName: 'EventGridThree'

  # Agent VM image name
  vmImageName: 'vs2017-win2016'

  # Working Directory
  workingDirectory: 'c'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzurePowerShell@4
  inputs:
    azureSubscription: '$(azureSubscription)'
    ScriptType: 'InlineScript'
    Inline: |
      Write-Host "Hello World from $Env:AGENT_NAME."
      Write-Host "My ID is $Env:AGENT_ID."
      Write-Host "AGENT_WORKFOLDER contents:"
      gci $Env:AGENT_WORKFOLDER
      Write-Host "AGENT_BUILDDIRECTORY contents:"
      gci $Env:AGENT_BUILDDIRECTORY
      Write-Host "BUILD_SOURCESDIRECTORY contents:"
      gci $Env:BUILD_SOURCESDIRECTORY
      Write-Host "Over and out."
      Write-Host $Env:BUILD_SOURCESDIRECTORY"/AAPStackARM/Deploy-AzTemplate.ps1"
       gci $Env:BUILD_SOURCESDIRECTORY"/AAPStackARM"
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@4
  inputs:
    azureSubscription: '$(azureSubscription)'
    ScriptType: 'FilePath'
    ScriptPath: ./AAPStackARM/Deploy-AzTemplate.ps1
    ScriptArguments:  -ArtifactStagingDirectory . -StorageAccountName 'AAPStack_SA' -Location eastus -TemplateFile ./AAPStackARM/AzureDeploy.json -TemplateParametersFile ./azuredeploy.parameters.json -ResourceGroupName AAPStack_RG
    azurePowerShellVersion: 'LatestVersion'
